package logm

import (
	"context"
	"log/slog"

	"uuid"
)

type contextKey struct{}

var loggerKey contextKey

// WithLogger stores a logger in context. A nil logger is ignored so callers do
// not accidentally make FromContext unusable.
func WithLogger(ctx context.Context, logger *slog.Logger) context.Context {
	if ctx == nil {
		ctx = context.Background()
	}
	if logger == nil {
		return ctx
	}
	return context.WithValue(ctx, loggerKey, logger)
}

// FromContext returns the context logger or slog.Default when absent.
func FromContext(ctx context.Context) *slog.Logger {
	if ctx != nil {
		if logger, ok := ctx.Value(loggerKey).(*slog.Logger); ok && logger != nil {
			return logger
		}
	}
	return slog.Default()
}

// NewRequestID returns a time-sortable UUIDv7 generated by the Go 1.27
// standard library.
func NewRequestID() string { return uuid.NewV7().String() }

// WithRequestID adds an explicit request ID to the context logger.
func WithRequestID(ctx context.Context, requestID string) context.Context {
	if ctx == nil {
		ctx = context.Background()
	}
	ctx = WithLogger(ctx, FromContext(ctx).With("request_id", requestID))
	return context.WithValue(ctx, requestIDKey, requestID)
}

// WithNewRequestID generates and stores a UUIDv7 request ID and returns the
// derived context. Use RequestID to retrieve the value when needed.
func WithNewRequestID(ctx context.Context) context.Context {
	return WithRequestID(ctx, NewRequestID())
}

// RequestID extracts the request ID stored by WithRequestID or
// WithNewRequestID. It returns an empty string when the context has no ID.
func RequestID(ctx context.Context) string {
	// slog.Logger intentionally does not expose its accumulated attrs. Keep the
	// value explicit in context as well so retrieval is allocation-free.
	if ctx != nil {
		if value, ok := ctx.Value(requestIDKey).(string); ok {
			return value
		}
	}
	return ""
}

type requestIDContextKey struct{}

var requestIDKey requestIDContextKey
